[book]
title = "Guide to Rustc Development"
author = "Rustc developers"
description = "A guide to developing rustc"

[build]
create-missing = false

[output.html]
git-repository-url = "https://github.com/longfangsong/rustc-dev-guide-cn"

[output.html.fold]
enable = true
level = 0

[output.linkcheck]
follow-web-links = true
exclude = [ "crates\\.io", "gcc\\.godbolt\\.org", "youtube\\.com", "youtu\\.be", "dl\\.acm\\.org", "cs\\.bgu\\.ac\\.il", "www\\.amazon\\.com", "www\\.rustaceans\\.org" ]
cache-timeout = 86400
warning-policy = "error"
